### ISSUE TITLE
Food disappear

### ISSUE THREAD

**Issue by soulofhan** [SLMT/rust-snake#1]
运行程序之后，在吃了两三个食物方块后，方块就消失了~
程序是我自己编译的，修改过窗口大小

After running the program, after eating two or three food boxes, the box disappears
The program is my own translation, modify the window size

**Comment by SLMT** [comment]
@soulofhan 是否可以更詳細地敘述一些細節呢？
例如代碼上改了甚麼，以及有甚麼其他異常之類的

因為我自己試了幾次沒有遇到這個問題

感謝您

**Comment by soulofhan** [comment]
嗯。。。窗口大小的数值改了，原本你的数值是20还是25的，我改大了，再编译的时候开始游戏，有时候食物就刷不出来了

黄广俊

2017年9月24日 00:55，"Yushan Lin" <notifications@github.com>写道：

**Comment by SLMT** [comment]
Merge request #2 fixed this bug.
