### ISSUE TITLE
I got error when run `cargo build`

### ISSUE THREAD

**Issue by yuer1727** [SLMT/rust-snake#3]
Compiling cocoa v0.9.2
error[E0282]: type annotations needed
   --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.9.2/src/appkit.rs:479:9
    |
479 |         msg_send![self, releaseGlobally];
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ consider giving `result` a type
    |
    = note: this error originates in the macro `msg_send` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
    --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.9.2/src/appkit.rs:2798:9
     |
2798 |         msg_send![self, setBezelStyle:style];
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ consider giving `result` a type
     |
     = note: this error originates in the macro `msg_send` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
    --> /Users/aligame/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.9.2/src/appkit.rs:3403:9
     |
3403 |         msg_send![self, setEditable:editable];
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ consider giving `result` a type
     |
     = note: this error originates in the macro `msg_send` (in Nightly builds, rThe compiler could not infer a type and aske

and then  I upgrade piston_window to  version  "0.120.0",  it works.

**Comment by SLMT** [comment]
Merge #4 has fixed the problem.
